// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBrj6oZpIff7V2AAQ6iIVfSgOcUZsicV94",
    authDomain: "speedy-010111.firebaseapp.com",
    projectId: "speedy-010111",
    storageBucket: "speedy-010111.firebasestorage.app",
    messagingSenderId: "955518756891",
    appId: "1:955518756891:android:8de559f5cfc0dac41e30be",
    measurementId: "8446562564",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrj6oZpIff7V2AAQ6iIVfSgOcUZsicV94',
    appId: '1:955518756891:android:be20d9f50d7161a91e30be',
    messagingSenderId: '955518756891',
    projectId: 'speedy-010111',
    storageBucket: 'speedy-010111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBrj6oZpIff7V2AAQ6iIVfSgOcUZsicV94",
    authDomain: "speedy-010111.firebaseapp.com",
    projectId: "speedy-010111",
    storageBucket: "speedy-010111.firebasestorage.app",
    messagingSenderId: "955518756891",
    appId: "1:955518756891:android:8de559f5cfc0dac41e30be",
    measurementId: "8446562564",
    androidClientId:
        '955518756891-qs4aci8amli72r9e1i2503gjrsmiaioq.apps.googleusercontent.com',
    iosClientId:
        '955518756891-uso4itqp8ogonimkjuf1menm0erqe9mi.apps.googleusercontent.com',
    iosBundleId: 'com.gcw.userapp',
  );
}
